/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CaresoukRouteImport } from './routes/caresouk'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as PolicySessionsRouteImport } from './routes/policy-sessions'
import { Route as ProgrammeRouteImport } from './routes/programme'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SpeakersRouteImport } from './routes/speakers'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminCheckInRouteImport } from './routes/admin/check-in'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminMessagesRouteImport } from './routes/admin/messages'
import { Route as AdminPartnersRouteImport } from './routes/admin/partners'
import { Route as AdminRegistrationsRouteImport } from './routes/admin/registrations'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminSpeakersRouteImport } from './routes/admin/speakers'
import { Route as ApiQrRegistrationIdRouteImport } from './routes/api/qr/$registrationId'
import { Route as ApiRegistrationsIndexRouteImport } from './routes/api/registrations/index'
import { Route as ApiRegistrationsResendRouteImport } from './routes/api/registrations/resend'
import { Route as ApiRegistrationsStatsRouteImport } from './routes/api/registrations/stats'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CaresoukRoute = CaresoukRouteImport.update({
  id: '/caresouk',
  path: '/caresouk',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicySessionsRoute = PolicySessionsRouteImport.update({
  id: '/policy-sessions',
  path: '/policy-sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammeRoute = ProgrammeRouteImport.update({
  id: '/programme',
  path: '/programme',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeakersRoute = SpeakersRouteImport.update({
  id: '/speakers',
  path: '/speakers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCheckInRoute = AdminCheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPartnersRoute = AdminPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRegistrationsRoute = AdminRegistrationsRouteImport.update({
  id: '/registrations',
  path: '/registrations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSpeakersRoute = AdminSpeakersRouteImport.update({
  id: '/speakers',
  path: '/speakers',
  getParentRoute: () => AdminRoute,
} as any)
const ApiQrRegistrationIdRoute = ApiQrRegistrationIdRouteImport.update({
  id: '/api/qr/$registrationId',
  path: '/api/qr/$registrationId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRegistrationsIndexRoute = ApiRegistrationsIndexRouteImport.update({
  id: '/api/registrations/',
  path: '/api/registrations/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRegistrationsResendRoute = ApiRegistrationsResendRouteImport.update({
  id: '/api/registrations/resend',
  path: '/api/registrations/resend',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRegistrationsStatsRoute = ApiRegistrationsStatsRouteImport.update({
  id: '/api/registrations/stats',
  path: '/api/registrations/stats',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/caresouk': typeof CaresoukRoute
  '/contact': typeof ContactRoute
  '/partners': typeof PartnersRoute
  '/policy-sessions': typeof PolicySessionsRoute
  '/programme': typeof ProgrammeRoute
  '/register': typeof RegisterRoute
  '/speakers': typeof SpeakersRoute
  '/admin/check-in': typeof AdminCheckInRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/speakers': typeof AdminSpeakersRoute
  '/admin/': typeof AdminIndexRoute
  '/api/qr/$registrationId': typeof ApiQrRegistrationIdRoute
  '/api/registrations/resend': typeof ApiRegistrationsResendRoute
  '/api/registrations/stats': typeof ApiRegistrationsStatsRoute
  '/api/registrations/': typeof ApiRegistrationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/caresouk': typeof CaresoukRoute
  '/contact': typeof ContactRoute
  '/partners': typeof PartnersRoute
  '/policy-sessions': typeof PolicySessionsRoute
  '/programme': typeof ProgrammeRoute
  '/register': typeof RegisterRoute
  '/speakers': typeof SpeakersRoute
  '/admin/check-in': typeof AdminCheckInRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/speakers': typeof AdminSpeakersRoute
  '/admin': typeof AdminIndexRoute
  '/api/qr/$registrationId': typeof ApiQrRegistrationIdRoute
  '/api/registrations/resend': typeof ApiRegistrationsResendRoute
  '/api/registrations/stats': typeof ApiRegistrationsStatsRoute
  '/api/registrations': typeof ApiRegistrationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/caresouk': typeof CaresoukRoute
  '/contact': typeof ContactRoute
  '/partners': typeof PartnersRoute
  '/policy-sessions': typeof PolicySessionsRoute
  '/programme': typeof ProgrammeRoute
  '/register': typeof RegisterRoute
  '/speakers': typeof SpeakersRoute
  '/admin/check-in': typeof AdminCheckInRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/speakers': typeof AdminSpeakersRoute
  '/admin/': typeof AdminIndexRoute
  '/api/qr/$registrationId': typeof ApiQrRegistrationIdRoute
  '/api/registrations/resend': typeof ApiRegistrationsResendRoute
  '/api/registrations/stats': typeof ApiRegistrationsStatsRoute
  '/api/registrations/': typeof ApiRegistrationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/caresouk'
    | '/contact'
    | '/partners'
    | '/policy-sessions'
    | '/programme'
    | '/register'
    | '/speakers'
    | '/admin/check-in'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/partners'
    | '/admin/registrations'
    | '/admin/settings'
    | '/admin/speakers'
    | '/admin/'
    | '/api/qr/$registrationId'
    | '/api/registrations/resend'
    | '/api/registrations/stats'
    | '/api/registrations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/caresouk'
    | '/contact'
    | '/partners'
    | '/policy-sessions'
    | '/programme'
    | '/register'
    | '/speakers'
    | '/admin/check-in'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/partners'
    | '/admin/registrations'
    | '/admin/settings'
    | '/admin/speakers'
    | '/admin'
    | '/api/qr/$registrationId'
    | '/api/registrations/resend'
    | '/api/registrations/stats'
    | '/api/registrations'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/caresouk'
    | '/contact'
    | '/partners'
    | '/policy-sessions'
    | '/programme'
    | '/register'
    | '/speakers'
    | '/admin/check-in'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/partners'
    | '/admin/registrations'
    | '/admin/settings'
    | '/admin/speakers'
    | '/admin/'
    | '/api/qr/$registrationId'
    | '/api/registrations/resend'
    | '/api/registrations/stats'
    | '/api/registrations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CaresoukRoute: typeof CaresoukRoute
  ContactRoute: typeof ContactRoute
  PartnersRoute: typeof PartnersRoute
  PolicySessionsRoute: typeof PolicySessionsRoute
  ProgrammeRoute: typeof ProgrammeRoute
  RegisterRoute: typeof RegisterRoute
  SpeakersRoute: typeof SpeakersRoute
  ApiQrRegistrationIdRoute: typeof ApiQrRegistrationIdRoute
  ApiRegistrationsResendRoute: typeof ApiRegistrationsResendRoute
  ApiRegistrationsStatsRoute: typeof ApiRegistrationsStatsRoute
  ApiRegistrationsIndexRoute: typeof ApiRegistrationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caresouk': {
      id: '/caresouk'
      path: '/caresouk'
      fullPath: '/caresouk'
      preLoaderRoute: typeof CaresoukRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policy-sessions': {
      id: '/policy-sessions'
      path: '/policy-sessions'
      fullPath: '/policy-sessions'
      preLoaderRoute: typeof PolicySessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programme': {
      id: '/programme'
      path: '/programme'
      fullPath: '/programme'
      preLoaderRoute: typeof ProgrammeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speakers': {
      id: '/speakers'
      path: '/speakers'
      fullPath: '/speakers'
      preLoaderRoute: typeof SpeakersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/check-in': {
      id: '/admin/check-in'
      path: '/check-in'
      fullPath: '/admin/check-in'
      preLoaderRoute: typeof AdminCheckInRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/partners': {
      id: '/admin/partners'
      path: '/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AdminPartnersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/registrations': {
      id: '/admin/registrations'
      path: '/registrations'
      fullPath: '/admin/registrations'
      preLoaderRoute: typeof AdminRegistrationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/speakers': {
      id: '/admin/speakers'
      path: '/speakers'
      fullPath: '/admin/speakers'
      preLoaderRoute: typeof AdminSpeakersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/qr/$registrationId': {
      id: '/api/qr/$registrationId'
      path: '/api/qr/$registrationId'
      fullPath: '/api/qr/$registrationId'
      preLoaderRoute: typeof ApiQrRegistrationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/registrations/': {
      id: '/api/registrations/'
      path: '/api/registrations'
      fullPath: '/api/registrations/'
      preLoaderRoute: typeof ApiRegistrationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/registrations/resend': {
      id: '/api/registrations/resend'
      path: '/api/registrations/resend'
      fullPath: '/api/registrations/resend'
      preLoaderRoute: typeof ApiRegistrationsResendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/registrations/stats': {
      id: '/api/registrations/stats'
      path: '/api/registrations/stats'
      fullPath: '/api/registrations/stats'
      preLoaderRoute: typeof ApiRegistrationsStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminCheckInRoute: typeof AdminCheckInRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminPartnersRoute: typeof AdminPartnersRoute
  AdminRegistrationsRoute: typeof AdminRegistrationsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSpeakersRoute: typeof AdminSpeakersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCheckInRoute: AdminCheckInRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminPartnersRoute: AdminPartnersRoute,
  AdminRegistrationsRoute: AdminRegistrationsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSpeakersRoute: AdminSpeakersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CaresoukRoute: CaresoukRoute,
  ContactRoute: ContactRoute,
  PartnersRoute: PartnersRoute,
  PolicySessionsRoute: PolicySessionsRoute,
  ProgrammeRoute: ProgrammeRoute,
  RegisterRoute: RegisterRoute,
  SpeakersRoute: SpeakersRoute,
  ApiQrRegistrationIdRoute: ApiQrRegistrationIdRoute,
  ApiRegistrationsResendRoute: ApiRegistrationsResendRoute,
  ApiRegistrationsStatsRoute: ApiRegistrationsStatsRoute,
  ApiRegistrationsIndexRoute: ApiRegistrationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
